train_name: "ResBase" #  model name

train:
  dataset: "FashionMNIST" #  dataset name
  new_training: True # 是否新一轮训练

  datasets_root: "./datasets"
  num_epoch:  100  #  number of epoch
  last:
    # 如果是继续训练，则需要指定上次记录的train_id
    id: ResBase_250517_2331
    # start epoch, 只有继续训练才生效,
    # 表示上次记录点的epoch ，否则默认是0
    start_epoch: 90
    # record_dir: "./record"
  

